import Header from "../components/Header";
import LotteryEntrance from "../components/LotteryEntrance";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by 0XApplepie" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#ebddff] to-[#3d3f61]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold font-mono tracking-tight text-white sm:text-[5rem]">
            Smart <span className="text-[hsl(280,100%,70%)]">Contract</span> Lottery
          </h1>
          <Head>
                <title>Smart Contract Lottery</title>
                <meta name="description" content="Our Smart Contract Lottery" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <LotteryEntrance />
        </div>
      </main>
    </>
  );
}
